@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

package "customer"{
class Customer{
-id
}

class SalesClerk{
}

Customer <<entity>>
SalesClerk <<entity>>
Address <<value object>>
Email <<value object>>
PhoneNumber <<value object>>
BirthDate <<value object>>
Delivering <<value object>>
Billing <<value object>>
VAT <<value object>>
Name <<value object>>
Gender <<value object>>
}

SalesClerk "1" -- "*" Customer : register >
Customer  --> "1" Email
Customer  --> "1" VAT
Customer  --> "1" PhoneNumber
Customer  --> "1" Name
Customer  --> "1" Gender
Customer  --> "0..1" BirthDate
Customer "1" -- "*" Address : residence >
Address <|-- Delivering
Address <|-- Billing
@enduml