@startuml
autonumber
'hide footbox


participant ":PersistenceContext" as PC
participant ":RepositoryFactory" as RF
participant ":OrderRepository" as OR


activate PC
PC -> RF : create()
activate RF
RF -> OR : create()
activate OR
deactivate OR
deactivate RF
|||
deactivate PC
@enduml