@startuml
autonumber
'hide footbox


participant ":PersistenceContext" as PC
participant ":RepositoryFactory" as RF
participant ":WarehouseRepository" as WR


activate PC
PC -> RF : create()
activate RF
RF -> WR : create()
activate WR
deactivate WR
deactivate RF
|||
deactivate PC
@enduml